Complete Project
SimbaWANGU/hello-rails-back-end pull request #2
Opened 2022-11-30 19:33 UTC by SimbaWANGU

In this PR, the following were completed:
- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action an rails route).

Link to Frontend PR [here](https://github.com/SimbaWANGU/hello_react_front_end/pull/2)

2022-11-30 21:18 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @SimbaWANGU, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have a correct link in the readme file. Make sure you have the following with correct link:
- In the README file for the frontend, students should provide a link to the Rails API (backend app).
- In the README file for the backend, you should find a link to the frontend part.
- In the repo for the frontend part - there should be PR with changes.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-30 22:18 UTC, sja-thedude requested changes
## Invalid Code Review Request ❌

Hi @SimbaWANGU, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have an updated readme template. Kindly make sure you use [this](https://github.com/microverseinc/readme-template#readme) template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-12-01 06:33 UTC, Ismailco approved these changes
### Hi @SimbaWANGU, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 06:33 UTC, Ismailco commented on app/controllers/application_controller.rb
> +  end
- [ ] [OPTIONAL] You can create a separate controller for greeting, this will make your controllers more organized (for a sample app like this it will not make a difference but keep in mind to use best practices all the time)

2022-12-01 06:34 UTC, merged